spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/auction-service
    username: root
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect